-- Daily supervisor summary delivery ledger.
-- Guarantees at-most-once delivery per agent and local calendar day.

create table if not exists public.nexo_bot_resumenes_envios (
  id bigint generated by default as identity primary key,
  agente_id uuid not null references public.nexo_bot_accesos(id) on delete cascade,
  local_date date not null,
  timezone text not null default 'Europe/Madrid',
  scheduled_for timestamptz,
  mensaje text not null,
  status text not null default 'pending'
    check (status in ('pending','sending','sent','error')),
  provider text not null default 'twilio',
  provider_message_id text,
  attempts integer not null default 0 check (attempts >= 0),
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  sent_at timestamptz,
  unique (agente_id, local_date)
);

create index if not exists nexo_bot_resumenes_envios_status_idx
  on public.nexo_bot_resumenes_envios(status, local_date);

alter table public.nexo_bot_resumenes_envios enable row level security;

comment on table public.nexo_bot_resumenes_envios is
  'Server-managed ledger for one daily supervisor WhatsApp summary per agent/local date.';
