-- Canonical reputation metrics owned by PostgreSQL/Supabase.
-- Supabase stores facts AND calculates deterministic reputation KPIs.
-- Nexo/Vercel consumes these results; interfaces do not recalculate them.

create table if not exists public.nexo_metric_validation_events (
  id bigint generated by default as identity primary key,
  metric_domain text not null,
  start_date date not null,
  end_date date not null,
  restaurant_count integer not null default 0,
  mismatch_count integer not null default 0,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.nexo_metric_validation_events enable row level security;

comment on table public.nexo_metric_validation_events is
  'Shadow validation events comparing Supabase canonical KPI results against legacy Nexo calculations during migration.';

create or replace function public.nexo_reputation_period_metrics(
  p_start date,
  p_end date,
  p_restaurant_ids bigint[] default null
)
returns table (
  restaurante_id bigint,
  total_resenas bigint,
  rating_sum numeric,
  media_exacta numeric,
  positivas bigint,
  neutras bigint,
  negativas bigint,
  atencion bigint,
  stars_1 bigint,
  stars_2 bigint,
  stars_3 bigint,
  stars_4 bigint,
  stars_5 bigint,
  ultima_resena timestamptz,
  operational_status text,
  source text,
  network_total_resenas bigint,
  network_rating_sum numeric,
  network_media_exacta numeric,
  network_positivas bigint,
  network_neutras bigint,
  network_negativas bigint,
  network_atencion bigint,
  network_total_restaurantes bigint,
  network_positive_pct numeric,
  network_negative_pct numeric,
  network_ultima_resena timestamptz
)
language sql
stable
set search_path = public
as $function$
with params as (
  select least(p_start, p_end) as start_date,
         greatest(p_start, p_end) as end_date
),
scoped_restaurants as (
  select r.id
  from public.restaurantes r
  where r.activo = true
    and (
      p_restaurant_ids is null
      or r.id = any(p_restaurant_ids)
    )
),
raw_reviews as (
  select
    s.id,
    s.review_id,
    s.restaurante_id,
    s.restaurante_nombre,
    s.autor,
    s.estrellas,
    s.comentario,
    s.fecha_resena,
    s.created_at,
    s.editada,
    s.fecha_ultima_edicion,
    nullif(btrim(s.review_id), '') as normalized_review_id,
    coalesce(s.fecha_resena, s.created_at) as original_ts,
    coalesce(s.fecha_resena, s.created_at)::date as original_date,
    case
      when s.editada is true and s.fecha_ultima_edicion is not null
        then s.fecha_ultima_edicion
      else coalesce(s.fecha_resena, s.created_at) at time zone 'Europe/Madrid'
    end as activity_ts,
    case
      when s.editada is true and s.fecha_ultima_edicion is not null
        then (s.fecha_ultima_edicion at time zone 'Europe/Madrid')::date
      else coalesce(s.fecha_resena, s.created_at)::date
    end as activity_date,
    lower(regexp_replace(btrim(coalesce(s.restaurante_nombre, '')), '\s+', ' ', 'g')) as restaurant_name_norm,
    lower(regexp_replace(btrim(coalesce(s.autor, '')), '\s+', ' ', 'g')) as author_norm,
    lower(regexp_replace(btrim(coalesce(s.comentario, '')), '\s+', ' ', 'g')) as comment_norm
  from public.resenas s
  join scoped_restaurants sr on sr.id = s.restaurante_id
  cross join params p
  where (
    case
      when s.editada is true and s.fecha_ultima_edicion is not null
        then (s.fecha_ultima_edicion at time zone 'Europe/Madrid')::date
      else coalesce(s.fecha_resena, s.created_at)::date
    end
  ) between p.start_date and p.end_date
),
dedupe_review_id as (
  select *
  from (
    select
      rr.*,
      row_number() over (
        partition by
          case
            when rr.normalized_review_id is not null
              then 'review_id:' || rr.normalized_review_id
            else 'row_id:' || rr.id::text
          end
        order by rr.original_ts desc nulls last, rr.id desc
      ) as rn
    from raw_reviews rr
  ) ranked
  where rn = 1
),
dedupe_content as (
  select *
  from (
    select
      d.*,
      row_number() over (
        partition by
          case
            when d.comment_norm = '' and d.author_norm = ''
              then 'row_id:' || d.id::text
            else
              'content:' ||
              coalesce(d.restaurante_id::text, '0') || ':' ||
              d.restaurant_name_norm || ':' ||
              coalesce(to_char(d.original_date, 'YYYY-MM-DD'), '') || ':' ||
              d.author_norm || ':' ||
              d.estrellas::text || ':' ||
              d.comment_norm
          end
        order by
          (d.normalized_review_id is not null) desc,
          d.original_ts desc nulls last,
          d.id desc
      ) as rn_content
    from dedupe_review_id d
  ) ranked
  where rn_content = 1
),
review_metrics as (
  select
    d.restaurante_id,
    count(*)::bigint as total_resenas,
    coalesce(sum(d.estrellas), 0)::numeric as rating_sum,
    count(*) filter (where d.estrellas >= 4)::bigint as positivas,
    count(*) filter (where d.estrellas = 3)::bigint as neutras,
    count(*) filter (where d.estrellas <= 2)::bigint as negativas,
    count(*) filter (where d.estrellas <= 3)::bigint as atencion,
    count(*) filter (where d.estrellas = 1)::bigint as stars_1,
    count(*) filter (where d.estrellas = 2)::bigint as stars_2,
    count(*) filter (where d.estrellas = 3)::bigint as stars_3,
    count(*) filter (where d.estrellas = 4)::bigint as stars_4,
    count(*) filter (where d.estrellas >= 5)::bigint as stars_5,
    max(d.original_ts at time zone 'Europe/Madrid') as ultima_resena
  from dedupe_content d
  group by d.restaurante_id
),
daily_metrics as (
  select
    k.restaurante_id,
    sum(k.total_resenas)::bigint as total_resenas,
    coalesce(sum(k.media * k.total_resenas), 0)::numeric as rating_sum,
    sum(k.positivas)::bigint as positivas,
    greatest(
      sum(k.total_resenas) - sum(k.positivas) - sum(k.negativas),
      0
    )::bigint as neutras,
    sum(k.negativas)::bigint as negativas,
    sum(k.negativas)::bigint as atencion,
    0::bigint as stars_1,
    0::bigint as stars_2,
    0::bigint as stars_3,
    0::bigint as stars_4,
    0::bigint as stars_5,
    (max(k.fecha)::timestamp at time zone 'Europe/Madrid') as ultima_resena
  from public.kpi_diario k
  join scoped_restaurants sr on sr.id = k.restaurante_id
  cross join params p
  where k.fecha between p.start_date and p.end_date
  group by k.restaurante_id
),
source_choice as (
  select
    case
      when exists (select 1 from dedupe_content) then 'resenas'
      when exists (select 1 from daily_metrics where total_resenas > 0) then 'kpi_diario'
      else 'empty'
    end as source
),
per_restaurant as (
  select
    sr.id as restaurante_id,
    case sc.source
      when 'resenas' then coalesce(rm.total_resenas, 0)
      when 'kpi_diario' then coalesce(dm.total_resenas, 0)
      else 0
    end::bigint as total_resenas,
    case sc.source
      when 'resenas' then coalesce(rm.rating_sum, 0)
      when 'kpi_diario' then coalesce(dm.rating_sum, 0)
      else 0
    end::numeric as rating_sum,
    case sc.source
      when 'resenas' then coalesce(rm.positivas, 0)
      when 'kpi_diario' then coalesce(dm.positivas, 0)
      else 0
    end::bigint as positivas,
    case sc.source
      when 'resenas' then coalesce(rm.neutras, 0)
      when 'kpi_diario' then coalesce(dm.neutras, 0)
      else 0
    end::bigint as neutras,
    case sc.source
      when 'resenas' then coalesce(rm.negativas, 0)
      when 'kpi_diario' then coalesce(dm.negativas, 0)
      else 0
    end::bigint as negativas,
    case sc.source
      when 'resenas' then coalesce(rm.atencion, 0)
      when 'kpi_diario' then coalesce(dm.atencion, 0)
      else 0
    end::bigint as atencion,
    case sc.source when 'resenas' then coalesce(rm.stars_1, 0) else 0 end::bigint as stars_1,
    case sc.source when 'resenas' then coalesce(rm.stars_2, 0) else 0 end::bigint as stars_2,
    case sc.source when 'resenas' then coalesce(rm.stars_3, 0) else 0 end::bigint as stars_3,
    case sc.source when 'resenas' then coalesce(rm.stars_4, 0) else 0 end::bigint as stars_4,
    case sc.source when 'resenas' then coalesce(rm.stars_5, 0) else 0 end::bigint as stars_5,
    case sc.source
      when 'resenas' then rm.ultima_resena
      when 'kpi_diario' then dm.ultima_resena
      else null
    end as ultima_resena,
    sc.source
  from scoped_restaurants sr
  cross join source_choice sc
  left join review_metrics rm on rm.restaurante_id = sr.id
  left join daily_metrics dm on dm.restaurante_id = sr.id
),
with_status as (
  select
    pr.*,
    case
      when pr.total_resenas = 0 then 0::numeric
      else pr.rating_sum / pr.total_resenas
    end as media_exacta,
    case
      when pr.total_resenas = 0 then 'watch'
      when (pr.rating_sum / pr.total_resenas) >= 4.4 then 'on_target'
      when (pr.rating_sum / pr.total_resenas) >= 4.0 then 'watch'
      else 'critical'
    end as operational_status
  from per_restaurant pr
),
network as (
  select
    coalesce(sum(ws.total_resenas), 0)::bigint as total_resenas,
    coalesce(sum(ws.rating_sum), 0)::numeric as rating_sum,
    coalesce(sum(ws.positivas), 0)::bigint as positivas,
    coalesce(sum(ws.neutras), 0)::bigint as neutras,
    coalesce(sum(ws.negativas), 0)::bigint as negativas,
    coalesce(sum(ws.atencion), 0)::bigint as atencion,
    count(*)::bigint as total_restaurantes,
    max(ws.ultima_resena) as ultima_resena
  from with_status ws
)
select
  ws.restaurante_id,
  ws.total_resenas,
  ws.rating_sum,
  ws.media_exacta,
  ws.positivas,
  ws.neutras,
  ws.negativas,
  ws.atencion,
  ws.stars_1,
  ws.stars_2,
  ws.stars_3,
  ws.stars_4,
  ws.stars_5,
  ws.ultima_resena,
  ws.operational_status,
  ws.source,
  n.total_resenas as network_total_resenas,
  n.rating_sum as network_rating_sum,
  case
    when n.total_resenas = 0 then 0::numeric
    else n.rating_sum / n.total_resenas
  end as network_media_exacta,
  n.positivas as network_positivas,
  n.neutras as network_neutras,
  n.negativas as network_negativas,
  n.atencion as network_atencion,
  n.total_restaurantes as network_total_restaurantes,
  case
    when n.total_resenas = 0 then 0::numeric
    else (n.positivas::numeric / n.total_resenas) * 100
  end as network_positive_pct,
  case
    when n.total_resenas = 0 then 0::numeric
    else (n.negativas::numeric / n.total_resenas) * 100
  end as network_negative_pct,
  n.ultima_resena as network_ultima_resena
from with_status ws
cross join network n
order by ws.restaurante_id;
$function$;

revoke all on function public.nexo_reputation_period_metrics(date, date, bigint[]) from public;
revoke all on function public.nexo_reputation_period_metrics(date, date, bigint[]) from anon;
revoke all on function public.nexo_reputation_period_metrics(date, date, bigint[]) from authenticated;
grant execute on function public.nexo_reputation_period_metrics(date, date, bigint[]) to service_role;

comment on function public.nexo_reputation_period_metrics(date, date, bigint[]) is
  'Canonical reputation KPI calculation. This is the numeric source of truth for Nexo period metrics.';
