-- Restaurant onboarding V1.
-- Makes restaurant IDs server-generated and tracks integration readiness.

create unique index if not exists restaurantes_place_id_unique
  on public.restaurantes(place_id)
  where place_id is not null and btrim(place_id) <> '';

create table if not exists public.restaurante_integraciones (
  id bigint generated by default as identity primary key,
  restaurante_id bigint not null references public.restaurantes(id) on delete cascade,
  provider text not null check (
    provider in ('google_maps','apify','google_business','storeace','other')
  ),
  status text not null default 'pending' check (
    status in ('pending','connected','syncing','error','disabled')
  ),
  external_ref text,
  config jsonb not null default '{}'::jsonb,
  last_sync_at timestamptz,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (restaurante_id, provider)
);

create index if not exists restaurante_integraciones_status_idx
  on public.restaurante_integraciones(provider,status);

alter table public.restaurante_integraciones enable row level security;

comment on table public.restaurante_integraciones is
  'Operational integration status per restaurant. Server-managed; client UI reads through authenticated Nexo APIs.';

comment on column public.restaurante_integraciones.status is
  'pending = configured in Nexo but external connection still incomplete; connected = verified working; syncing = active sync; error = action required.';
