-- Safe fallback for first review of a restaurant whose Google place_id
-- is not known yet. Explicit aliases are server-managed and only used when
-- the normal place_id assignment did not find a restaurant.

create table if not exists public.restaurante_fuente_aliases (
  id bigint generated by default as identity primary key,
  restaurante_id bigint not null references public.restaurantes(id) on delete cascade,
  fuente text not null default 'apify',
  campo text not null default 'direccion_contains'
    check (campo in ('direccion_contains')),
  valor text not null,
  activo boolean not null default true,
  created_at timestamptz not null default now(),
  unique (restaurante_id, fuente, campo, valor)
);

alter table public.restaurante_fuente_aliases enable row level security;

comment on table public.restaurante_fuente_aliases is
  'Temporary/explicit ingestion aliases used to learn a provider place_id safely from the first matching observation.';

create or replace function public.asignar_restaurante_id()
returns trigger
language plpgsql
as $function$
declare
  v_restaurante_id bigint;
  v_match_count integer;
  v_normalized_address text;
begin
  -- Canonical path: provider place_id.
  if NEW.restaurante_id is null and NEW.place_id is not null then
    select id
      into NEW.restaurante_id
    from public.restaurantes
    where place_id = NEW.place_id
    limit 1;
  end if;

  -- Safe onboarding fallback: only explicit active aliases and only when
  -- exactly one restaurant matches the incoming address.
  if NEW.restaurante_id is null
     and NEW.direccion is not null
     and btrim(NEW.direccion) <> '' then

    v_normalized_address := regexp_replace(
      translate(lower(NEW.direccion), 'áéíóúüñ', 'aeiouun'),
      '[^a-z0-9]+',
      '',
      'g'
    );

    select count(*), min(a.restaurante_id)
      into v_match_count, v_restaurante_id
    from public.restaurante_fuente_aliases a
    where a.activo = true
      and a.campo = 'direccion_contains'
      and (a.fuente = coalesce(NEW.fuente, 'apify') or a.fuente = '*')
      and v_normalized_address like '%' || regexp_replace(
        translate(lower(a.valor), 'áéíóúüñ', 'aeiouun'),
        '[^a-z0-9]+',
        '',
        'g'
      ) || '%';

    if v_match_count = 1 then
      NEW.restaurante_id := v_restaurante_id;

      -- Learn the provider place_id once. The unique place_id index prevents
      -- accidental reuse across restaurants.
      if NEW.place_id is not null and btrim(NEW.place_id) <> '' then
        update public.restaurantes
        set place_id = NEW.place_id
        where id = v_restaurante_id
          and (place_id is null or btrim(place_id) = '');

        -- Once the place_id is learned the alias is no longer needed.
        update public.restaurante_fuente_aliases
        set activo = false
        where restaurante_id = v_restaurante_id
          and activo = true;
      end if;

      -- Record verified provider connectivity from the actual observation.
      begin
        if NEW.place_id is not null and btrim(NEW.place_id) <> '' then
          insert into public.restaurante_integraciones (
            restaurante_id, provider, status, external_ref, last_sync_at, updated_at
          )
          values (
            v_restaurante_id, 'google_maps', 'connected', NEW.place_id, now(), now()
          )
          on conflict (restaurante_id, provider)
          do update set
            status = 'connected',
            external_ref = excluded.external_ref,
            last_sync_at = excluded.last_sync_at,
            last_error = null,
            updated_at = now();
        end if;

        if lower(coalesce(NEW.fuente, '')) like '%apify%' then
          insert into public.restaurante_integraciones (
            restaurante_id, provider, status, external_ref, last_sync_at, updated_at
          )
          values (
            v_restaurante_id, 'apify', 'connected', NEW.place_id, now(), now()
          )
          on conflict (restaurante_id, provider)
          do update set
            status = 'connected',
            external_ref = coalesce(excluded.external_ref, public.restaurante_integraciones.external_ref),
            last_sync_at = excluded.last_sync_at,
            last_error = null,
            updated_at = now();
        end if;
      exception when others then
        -- Integration telemetry must never block ingestion.
        null;
      end;
    end if;
  end if;

  return NEW;
end;
$function$;
