-- DESIGN ONLY: do not apply to production until shadow validation is complete.
-- Review identity/version history for immutable reputation periods.

create table if not exists public.resena_logicas (
  id bigint generated by default as identity primary key,
  restaurante_id bigint not null references public.restaurantes(id),
  provider text not null default 'google',
  provider_place_id text not null,
  provider_reviewer_id text not null,
  current_provider_review_id text,
  current_stars smallint check (current_stars between 1 and 5),
  current_comment text,
  reviewer_name text,
  reviewer_url text,
  review_url text,
  first_published_at timestamptz,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  last_changed_at timestamptz,
  status text not null default 'active' check (status in ('active','possibly_hidden','hidden')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (provider, provider_place_id, provider_reviewer_id)
);

create table if not exists public.resena_provider_ids (
  id bigint generated by default as identity primary key,
  resena_logica_id bigint not null references public.resena_logicas(id) on delete cascade,
  provider text not null default 'google',
  provider_review_id text not null,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  link_status text not null default 'confirmed' check (link_status in ('confirmed','candidate','rejected')),
  link_reason text,
  confidence numeric(4,3) check (confidence is null or (confidence >= 0 and confidence <= 1)),
  evidence jsonb not null default '{}'::jsonb,
  unique (provider, provider_review_id)
);

create table if not exists public.resena_versiones (
  id bigint generated by default as identity primary key,
  resena_logica_id bigint not null references public.resena_logicas(id) on delete cascade,
  version integer not null check (version > 0),
  provider_review_id text,
  stars smallint not null check (stars between 1 and 5),
  comment text,
  content_fingerprint text not null,
  event_type text not null check (event_type in ('new','edited','recreated')),
  published_at timestamptz,
  detected_at timestamptz not null default now(),
  valid_from timestamptz not null default now(),
  valid_to timestamptz,
  unique (resena_logica_id, version),
  unique (resena_logica_id, content_fingerprint)
);

create index if not exists resena_versiones_logical_detected_idx
  on public.resena_versiones (resena_logica_id, detected_at desc);

create table if not exists public.reputation_period_closures (
  id bigint generated by default as identity primary key,
  restaurante_id bigint not null references public.restaurantes(id),
  period_type text not null check (period_type in ('week','month')),
  period_start date not null,
  period_end date not null,
  review_count integer not null default 0,
  positive_count integer not null default 0,
  neutral_count integer not null default 0,
  negative_count integer not null default 0,
  average_rating numeric(4,2),
  edits_count integer not null default 0,
  edits_improved integer not null default 0,
  edits_worsened integer not null default 0,
  closed_at timestamptz not null default now(),
  source text not null default 'nexo',
  unique (restaurante_id, period_type, period_start, period_end)
);

comment on table public.resena_logicas is
  'Current state of one logical Google review: one provider account per Google place.';
comment on table public.resena_provider_ids is
  'Provider review IDs observed for a logical review, including candidate links that require reconciliation.';
comment on table public.resena_versiones is
  'Immutable review versions. Never update historical content; insert a new version.';
comment on table public.reputation_period_closures is
  'Immutable KPI closure for completed reputation periods. Later review edits must not rewrite it.';
