-- LIVE SHADOW MODE ONLY.
-- This table observes review identity decisions without changing resenas, reports, alerts or WhatsApp.

create table if not exists public.review_identity_shadow_events (
  id bigint generated by default as identity primary key,
  provider text not null default 'google',
  restaurante_id bigint references public.restaurantes(id),
  place_id text not null,
  reviewer_id text not null,
  provider_review_id text not null,
  stars smallint not null check (stars between 1 and 5),
  comment text,
  content_fingerprint text not null,
  published_at timestamptz,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  reviewer_url text,
  review_url text,
  business_url text,
  decision text not null check (
    decision in ('baseline','new','edited','recreated','candidate')
  ),
  reason text not null,
  matched_event_id bigint references public.review_identity_shadow_events(id),
  evidence jsonb not null default '{}'::jsonb,
  source text not null default 'make-shadow',
  source_run_id text,
  created_at timestamptz not null default now()
);

create index if not exists review_identity_shadow_review_id_idx
  on public.review_identity_shadow_events (provider, provider_review_id, last_seen_at desc);

create index if not exists review_identity_shadow_candidate_idx
  on public.review_identity_shadow_events (
    provider, place_id, reviewer_id, last_seen_at desc
  );

create index if not exists review_identity_shadow_decision_idx
  on public.review_identity_shadow_events (decision, created_at desc);

alter table public.review_identity_shadow_events enable row level security;

comment on table public.review_identity_shadow_events is
  'Shadow-only observations used to validate review identity/version rules. It must not drive production KPIs, alerts or reports.';

insert into public.review_identity_shadow_events (
  provider,
  restaurante_id,
  place_id,
  reviewer_id,
  provider_review_id,
  stars,
  comment,
  content_fingerprint,
  published_at,
  first_seen_at,
  last_seen_at,
  reviewer_url,
  decision,
  reason,
  evidence,
  source
)
select
  'google',
  r.restaurante_id,
  r.place_id,
  substring(r.url from '/contrib/([0-9]+)'),
  r.review_id,
  r.estrellas,
  r.comentario,
  r.estrellas::text || '|' ||
    lower(regexp_replace(trim(coalesce(r.comentario, '')), '\s+', ' ', 'g')),
  r.fecha_resena at time zone 'Europe/Madrid',
  coalesce(r.created_at at time zone 'Europe/Madrid', now()),
  coalesce(r.created_at at time zone 'Europe/Madrid', now()),
  r.url,
  'baseline',
  'initial-production-snapshot',
  jsonb_build_object(
    'source_table', 'resenas',
    'resena_id', r.id,
    'editada', r.editada,
    'fecha_ultima_edicion', r.fecha_ultima_edicion
  ),
  'baseline-resenas'
from public.resenas r
where r.place_id is not null
  and r.place_id <> ''
  and r.review_id is not null
  and r.url like '%/contrib/%'
  and not exists (
    select 1
    from public.review_identity_shadow_events s
    where s.provider = 'google'
      and s.provider_review_id = r.review_id
      and s.decision = 'baseline'
  );
